### ISSUE TITLE
cannot get anymore int of enumerator class (alpha2)

### ISSUE THREAD

**Issue by maxcapodi78** [pythonnet/pythonnet#1809]
### Environment

-   Pythonnet version: 3.0.0 Alpha 2
-   Python version: 3.9
-   Operating System: Windows
-   .NET Runtime:

### Details

-   Describe what you were trying to get done.

    In v2.5.2 I'm able to get a C# Enumerator and get the int value. In alpha 2 it seems that the full enumerator class is returned but the int command is not working.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    my_enum = csharp_object.GetObjType()
    int(my_enum) --> Failing now, working before
```

-   If there was a crash, please include the traceback here.

```python
    cannot get int of object of class ComponentType (name of enumerator class)
```

**Comment by filmor** [comment]
You mean `enum`, right? An [`Enumerator`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerator?view=net-6.0) is a very different thing.

This issue should be fixed on the current master (if you have the .NET SDK installed, you can install it using `pip install git+https://github.com/pythonnet/pythonnet`, I'll cut it as `rc1` this weekend (see #1661).

Thanks for the report, and feel free to reopen if this doesnot work for you :)

**Comment by maxcapodi78** [comment]
Hi @filmor I've checked and the problem is still there. now it's even worst because it is making crashing the debugger.
![image](https://user-images.githubusercontent.com/77293250/172624444-a8d4291c-7f15-4b7a-8797-c35592b98b51.png)

**Comment by maxcapodi78** [comment]
@filmor I cannot reopen the PR since you have to do it.

**Comment by maxcapodi78** [comment]
I've created another issue. We can keep this one closed
