### ISSUE TITLE
c# <-> python dictionary converter

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#623]
https://stackoverflow.com/questions/48689604/calling-into-python-code-using-pythonnet-from-c-sharp-and-custom-c-sharp-classes

**Comment by yagweb** [comment]
This function is similar to the function I proposed here #484. These two functions can be  integrated into single one，“How to convert between python objects and CLR objects dynamically？”

Based on my code before, I just wrote a new [PyConverter](https://github.com/yagweb/pythonnetLab/blob/master/pynetLab/PyConverter.cs) here. I can make a PR if this design is accepted.

It can be used [in these ways](https://github.com/yagweb/pythonnetLab/blob/master/Test/TestPyConverter.cs),

1. Convert between [Python list and Clr List\<T\>][Test1] dynamically;
2. Convert between [Python dict and Clr Dictionary<K, V>][Test2] dynamically;
3. Convert between [Python  object and Clr object][Test3], looks like Serialize and Deserialize.
4. Convert any [complex objects][Test4], such as nested dictionaries, lists and objects etc.
4. It's extensible. Users can [define his own PyClrType][Func1].

[Test1]: https://github.com/yagweb/pythonnetLab/blob/aba0011a33812b304537f6f3b6a14e69bfab1787/Test/TestPyConverter.cs#L70-L92
[Test2]: https://github.com/yagweb/pythonnetLab/blob/aba0011a33812b304537f6f3b6a14e69bfab1787/Test/TestPyConverter.cs#L94-L119
[Test3]: https://github.com/yagweb/pythonnetLab/blob/aba0011a33812b304537f6f3b6a14e69bfab1787/Test/TestPyConverter.cs#L39-L68
[Test4]: https://github.com/yagweb/pythonnetLab/blob/aba0011a33812b304537f6f3b6a14e69bfab1787/Test/TestPyConverter.cs#L121-L169
[Func1]: https://github.com/yagweb/pythonnetLab/blob/aba0011a33812b304537f6f3b6a14e69bfab1787/Test/TestPyConverter.cs#L23-L37

For this issue from stackoverflow, we can use the PyConverter in this way,

First [define a PyConverter]() according to needs,
```
public PyConverter NewMyDictConverter()
{
    using (Py.GIL())
    {
        var converter = new PyConverter(); 
        converter.AddListType();
        converter.Add(new StringType());
        converter.Add(new Int64Type());
        converter.Add(new Int32Type());
        converter.Add(new FloatType());
        converter.Add(new DoubleType());
        converter.AddDictType<string, object>();
        return converter;
    }
}

```

Then, we can use this converter to convert a Clr Dictionary into a Python Dictionary, and vice versa.
```

using (Py.GIL())
{  
    //create a instance of PyConverter                
    var converter = NewMyDictConverter();

    var scope = Py.CreateScope();
    scope.Exec(
         "a={'0': 1, '1': [1, \"2\"]}"
    );
    dynamic a = scope.Get("a");  // mock a python dictionary

    var b = converter.ToClr(a);   //Convert python dict to Clr Dictionary<string, object>

    var c = converter.ToPython(b);  // Convert Clr Dictionary to python dict
    object c0 = c["0"];
    object c1 = c["1"];

    var d = converter.ToClr(c);
    object d0 = d["0"];
    object d1 = d["1"];

    scope.Dispose();
}
```

**Comment by denfromufa** [comment]
@yagweb when you mention conversion happens "dynamically", do you mean the conversion happens at runtime or even later when the corresponding value/field is accessed?

**Comment by yagweb** [comment]
@denfromufa "dynamically" here means the conversion happens at runtime. 

It‘s opposite to "static": we know the type of the value/field in coding phase, so we directly use the PyInt etc. in the code. 

There are three drawbacks of this hard coding method,

1. We need to define lots of transformation codes which have similar structure;
2. These codes are completely dependent on the specific data structure, so it's hard to maintenance;
3. Sometimes we don’t know the type in coding phase, for example, for a list of type List<object>, we don't know the types of its element until runtime.


The work steps of PyConverter are,


- at first recognize the type of the object at runtime, or accept a given type （static）, 
- then use the type to find a proper converter, (e.g. Python int can be converted into Clr Int32/Int64 etc.)
- at last call the method and obtain the return value.

**Comment by denfromufa** [comment]
@yagweb i have not tested your converter API yet, but this looks promising. regarding preparing a PR, there is too much activity currently. i would wait until we stabilize .net core support in few weeks.

**Comment by kostjaaa** [comment]
Have you tested this yet? It looks quite promising and I would like to use it. 
Would this be licensed under any terms?

**Comment by denfromufa** [comment]
@kostjaaa feel free to submit a PR, but make a summary of what you would like to achieve first.

**Comment by sschukat** [comment]
I had a similar problem but solved it using Python code, which works with the current release
See the [netdict](https://github.com/sschukat/PyNetExamples/blob/master/PythonModules/netdict.py) example.

**Comment by jiajiawei** [comment]
I add a method to convert dynamically in 'converter.cs' 

![image](https://user-images.githubusercontent.com/10414815/67137189-c8705580-f263-11e9-85e1-727b0f928803.png)

`        private static bool ToDict(IntPtr value, out object result, bool setError)
        {
            result = null;
            var obType = typeof(object);
            var keys = Runtime.PyDict_Keys(value);
            var IterObject = Runtime.PyObject_GetIter(keys);

            if (IterObject == IntPtr.Zero)
            {
                if (setError)
                {
                    SetConversionError(value, obType);
                }
                return false;
            }

            var dict = new Dictionary<object, object>();
            IntPtr childKey;

            while ((childKey = Runtime.PyIter_Next(IterObject)) != IntPtr.Zero)
            {
                object objKey;
                object objValue = null;

                if (!ToManaged(childKey, obType, out objKey, true))
                {
                    Runtime.XDecref(childKey);
                    return false;
                }

                var childValue = Runtime.PyDict_GetItem(value, childKey);
                if (childValue != IntPtr.Zero)
                {
                    if (!ToManaged(childValue, typeof(object), out objValue, true))
                    {
                        Runtime.XDecref(childValue);
                        return false;
                    }
                }

                dict[objKey] = objValue;
                Runtime.XDecref(childKey);
                Runtime.XDecref(childValue);
            }
            Runtime.XDecref(IterObject);
            Runtime.XDecref(keys);

            result = dict;
            return true;
        }`

**Comment by lostmsu** [comment]
This should now be fixed in 3.0

**Comment by siegfriedpammer** [comment]
> This should now be fixed in 3.0

When working with a `typing.Dict[str, str]` and `Dictionary<string, string>` I still get

> TypeError: 'dict' value cannot be converted to System.Collections.Generic.Dictionary`2[System.String,System.String]

on Python.NET 3.0.3

Looking at the source code it seems there is a PyDict wrapper, but it is not used in any of the Converter logic. Are there any plans to add built-in conversion support for dictionaries?

If it is supposed to work, an example show-casing the correct way to assign a python dictionary to an managed property accepting Dictionary<TKey, TValue> or IDictionary<TKey, TValue> or IReadOnlyDictionary<TKey, TValue> would be highly appreciated.

If only Python.NET was more "user-friendly"... don't get me wrong, it is doing an awesome job with most things, there are just some rough edges and unfortunately I already spent countless hours figuring out these things without much success...

Thanks!

**Comment by nwoolls** [comment]
> This should now be fixed in 3.0

Any details on how this was fixed in 3.0? How are we meant to take a dictionary from python and convert it into a C# `Dictionary<T,T>`?

**Comment by iFreilicht** [comment]
@lostmsu please reopen this issue, it is not fixed in Python.Net 3.0.5, the error message by @siegfriedpammer is still accurate.
