### ISSUE TITLE
Cannot run twice; Unity crashes after running more than once

### ISSUE THREAD

**Issue by off99555** [pythonnet/pythonnet#701]
### Environment

-   Pythonnet version: 2.3.0 py35
-   Python version: 3.5.4
-   Operating System: Windows 10

### Details

I want to run this code on my Unity project:
```cs
using Python.Runtime;
using UnityEngine;

public class TestLib : MonoBehaviour
{
    // Use this for initialization
    private void Start()
    {
        print("initializing python");
        PythonEngine.Initialize();
        print("running python code");
        using (Py.GIL())
        {
            dynamic np = Py.Import("numpy");
            print(np.cos(np.pi * 2));
        }

        print("Destroying python engine");
        PythonEngine.Shutdown();
    }
}
```
Here's the output:
![2018-07-06_05-02-13](https://user-images.githubusercontent.com/15215732/42350302-1659992a-80da-11e8-929f-19352fa80e9f.png)

It's able to run once but when I try to run it again, Unity editor crashes.

Here's the entire process:
I open Unity. Inside it, I click *play* to run this code, it works. And then I stop, and then I run the code again, Unity crashes.

#### Reasoning
- I'm suspecting that it's because python is still running in the background when I stop the game session.
But I tried Initialize() and Shutdown() twice in the code and it works (if I run it once). So I think it's not shutting down issue. It's something else that I cannot figure out.
- This error depends on the python code for sure. If I remove the python part and run, it would be able to run as many times as I want.
- It might also be a threading issue which I don't understand.

What are the possible causes and fixes?

**Comment by filmor** [comment]
It could be that this is the issue that is supposedly fixed by this PR: #697

**Comment by off99555** [comment]
We could close this issue for now. I don't have time to test that new PR yet. Anyone can reopen this if you find that the bug is not yet solved.

**Comment by lassond** [comment]
I am not entirely sure the case is the same, but I am currently completing #2/2 fixes for similar crashes. The first fix will be under review soon:
https://github.com/pythonnet/pythonnet/issues/714

**Comment by felipepedroso** [comment]
I'm still facing this crash 😢 
 
OS: Windows 10
Unity: 2019.3.0f6
Python 3.7.6

I installed pythonnet using `pip install` on a virtualenv inside the `Assets` folder.

**Comment by jackyangzzh** [comment]
I can confirm this crash exists in Unity 2019.3.3, Python 3,8.0. I am running very similar code and it also crashes the second time I run the script

**Comment by lostmsu** [comment]
This should be fixed in master with https://github.com/pythonnet/pythonnet/pull/958
You have to use soft shutdown though to prevent Python from being unloaded.
AFAIK, numpy does not support being unloaded.

**Comment by jackyangzzh** [comment]
An update: #958 fixes it. Now I can run numpy many times without any crash

**Comment by benoithudson** [comment]
Sure, and perhaps we can add the bug report code to @BadSingleton's unit tests.

**Comment by akaimody123** [comment]
Hi, this maybe not a pythonnet problem, but I wonder if you could give me some advice on that? I'm using "Keras.NET" in Unity3d, which uses "pythonnet_standard_py38_win" which is related with pythonnet. I'm facing the exact same problem here--It only allows me to run unity once and then it crashes. I tried to follow #958 by adding "PythonEngine.Initialize(softShutdown: true)" but it says "the best overload for initialize does not have a parameter named softShutDown". I'm very new to .NET and I would appreciate if you can give me some advice!

**Comment by lostmsu** [comment]
@akaimody123 "related to pythonnet" here means they took an old Python.NET and forked it. We do not support their fork. Please, contact authors of Keras.NET.

**Comment by Laur-Ivan** [comment]
Hello. Sorry if I'm reviving an old thread, but this exact same thing happens to me too. Every second time I hit play, my Unity editor crashes.
Can you explain more exactly how to fix it? 
Thanks a lot!

**Comment by benoithudson** [comment]
Unity provides an experimental package for Python now (based on Python.NET): https://docs.unity3d.com/Packages/com.unity.scripting.python@4.0/manual/index.html

Maybe try that? It solves a lot of the difficulty of getting things initialized properly.
